I'm really bored of the hoisters in Fabricord
FabricMC/fabric-discord-bot pull request #35
Opened 2020-12-16 18:03 UTC by LambdAurora

And multiple people already suggested multiple times to rename the hoisters.

This strategy is inspired from the strategy used on Jellysquid's Discord.

2020-12-17 20:37 UTC, i509VCB commented
I will give this a look

2020-12-17 20:40 UTC, gdude2002 commented
This will conflict with [the nickname stuff in the Infractions extension](https://github.com/FabricMC/fabric-discord-bot/blob/kord-0.7/src/main/kotlin/net/fabricmc/bot/extensions/InfractionsExtension.kt#L855) as nick-locked users could cause some nickname looping if a staff member uses the `?nick` command to nick someone to a bad nickname.

2020-12-18 11:37 UTC, redcreeper14385 requested changes

2020-12-18 11:37 UTC, redcreeper14385 commented on src/main/kotlin/net/fabricmc/bot/extensions/NicknameExtension.kt
> +     * Renames the member to "Z ; dumb hoist name".
I do not think we should send them to the bottom. This is moderation, not trolling.

2020-12-18 11:37 UTC, redcreeper14385 commented on src/main/kotlin/net/fabricmc/bot/extensions/NicknameExtension.kt
> +private val NAME_REGEX = Regex("^[!.\"+(-]")
Aren't there other characters which are not listed here which can hoist, like `%`?

2020-12-18 15:50 UTC, closed without merging